name: Setup GCC
description: Setup GCC

inputs:
  version:
    description: GCC version to install
    required: false
    default: latest
  cc:
    description: Set up cc/gcc/c++/g++/gcov executables
    required: false
    default: "true"
  env:
    description: Set up CC/CXX/GCOV environment variables
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup GCC VERSION
      shell: bash
      run: |
        GCC_VERSION="${{ inputs.version }}"

        if [[ "${GCC_VERSION}" == "latest" ]]; then
          GCC_VERSION="12"
        fi

        echo "GCC_VERSION=${GCC_VERSION}" >> $GITHUB_ENV

    - name: Install GCC For Ubuntu
      shell: bash
      if: runner.os == 'ubuntu'
      run: |
        sudo apt update
        sudo apt install -y \
          gcc-${{ env.GCC_VERSION }} \
          g++-${{ env.GCC_VERSION }}

    - name: Install GCC For macOS
      shell: bash
      if: runner.os == 'macos'
      run: |
        brew install gcc@${{ env.GCC_VERSION }}

    - name: Set CC And Env
      shell: bash
      run: |
        if [[ "${{ inputs.cc }}" == "true" ]]; then
          GCC_PATH=$(which gcc-${{ env.GCC_VERSION }})
          GXX_PATH=$(which g++-${{ env.GCC_VERSION }})
          GCOV_PATH=$(which gcov-${{ env.GCOV_VERSION }})

          ln -sf "${GCC_PATH}" /usr/local/bin/cc
          ln -sf "${GCC_PATH}" /usr/local/bin/gcc
          ln -sf "${GXX_PATH}" /usr/local/bin/c++
          ln -sf "${GXX_PATH}" /usr/local/bin/g++
          ln -sf "${GCOV_PATH}" /usr/local/bin/gcov
        fi

        if [[ "${{ inputs.env }}" == "true" ]]; then
          echo "CC=gcc-${{ env.GCC_VERSION }}" >>$GITHUB_ENV
          echo "CXX=g++-${{ env.GCC_VERSION }}" >>$GITHUB_ENV
          echo "GCOV=gcov-${{ env.GCC_VERSION }}" >>$GITHUB_ENV
        fi

branding:
  icon: "box"
  color: "green"
