# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - 11
          - 12
          - latest

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: ./
        with:
          version: "${{ matrix.version }}"

      - name: Test
        run: |
          which $CC
          which $CXX
          $CC --version
          $CXX --version

          which gcc
          which g++
          gcc --version
          g++ --version

          which cc
          cc --version
          which c++
          c++ --version

          which gcov
          gcov --version
