# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
  pull_request:

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version:
          - 11
          - 12
          - latest
    runs-on: "${{ matrix.os }}"
    name: "Test: ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: ./
        with:
          version: "${{ matrix.version }}"
          cc: 1

      - name: Test
        run: |
          which gcc
          which g++
          gcc --version
          g++ --version
